/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LeagueStandingData,
    LeagueStandingDataFromJSON,
    LeagueStandingDataFromJSONTyped,
    LeagueStandingDataToJSON,
} from './LeagueStandingData';
import {
    StageGroup,
    StageGroupFromJSON,
    StageGroupFromJSONTyped,
    StageGroupToJSON,
} from './StageGroup';
import {
    StageGroupWithStandingAllOf,
    StageGroupWithStandingAllOfFromJSON,
    StageGroupWithStandingAllOfFromJSONTyped,
    StageGroupWithStandingAllOfToJSON,
} from './StageGroupWithStandingAllOf';

/**
 * 
 * @export
 * @interface StageGroupWithStanding
 */
export interface StageGroupWithStanding {
    /**
     * Unique resource identifier
     * @type {number}
     * @memberof StageGroupWithStanding
     */
    id: number;
    /**
     * Human readable name of the Group
     * @type {string}
     * @memberof StageGroupWithStanding
     */
    name: string;
    /**
     * The order in the stage of the group
     * @type {number}
     * @memberof StageGroupWithStanding
     */
    orderInStage?: number;
    /**
     * League Standing for the StageGroup if available and requested
     * @type {Array<LeagueStandingData>}
     * @memberof StageGroupWithStanding
     */
    standing?: Array<LeagueStandingData>;
}

export function StageGroupWithStandingFromJSON(json: any): StageGroupWithStanding {
    return StageGroupWithStandingFromJSONTyped(json, false);
}

export function StageGroupWithStandingFromJSONTyped(json: any, ignoreDiscriminator: boolean): StageGroupWithStanding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'orderInStage': !exists(json, 'order_in_stage') ? undefined : json['order_in_stage'],
        'standing': !exists(json, 'standing') ? undefined : ((json['standing'] as Array<any>).map(LeagueStandingDataFromJSON)),
    };
}

export function StageGroupWithStandingToJSON(value?: StageGroupWithStanding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'order_in_stage': value.orderInStage,
        'standing': value.standing === undefined ? undefined : ((value.standing as Array<any>).map(LeagueStandingDataToJSON)),
    };
}

