/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TeamPlayerStatistics,
    TeamPlayerStatisticsFromJSON,
    TeamPlayerStatisticsFromJSONTyped,
    TeamPlayerStatisticsToJSON,
} from './TeamPlayerStatistics';

/**
 * 
 * @export
 * @interface TeamPlayerSeasonStatisticsAllOf
 */
export interface TeamPlayerSeasonStatisticsAllOf {
    /**
     * 
     * @type {Array<TeamPlayerStatistics>}
     * @memberof TeamPlayerSeasonStatisticsAllOf
     */
    items?: Array<TeamPlayerStatistics>;
}

export function TeamPlayerSeasonStatisticsAllOfFromJSON(json: any): TeamPlayerSeasonStatisticsAllOf {
    return TeamPlayerSeasonStatisticsAllOfFromJSONTyped(json, false);
}

export function TeamPlayerSeasonStatisticsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamPlayerSeasonStatisticsAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(TeamPlayerStatisticsFromJSON)),
    };
}

export function TeamPlayerSeasonStatisticsAllOfToJSON(value?: TeamPlayerSeasonStatisticsAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(TeamPlayerStatisticsToJSON)),
    };
}

