/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { BlacklistDto } from '../models';
import { BlacklistKeyDto } from '../models';
import { NotFoundError } from '../models';
/**
 * BlacklistApi - axios parameter creator
 * @export
 */
export const BlacklistApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Remove blacklist record by id.
         * @summary Remove the specified resource from storage.
         * @param {string} id Unique identifier of the resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2BlacklistIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling v2BlacklistIdDelete.');
            }
            const localVarPath = `/v2/blacklist/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Bulk find in blacklist table and return matching entries by the unique blacklist key.
         * @param {Array<BlacklistKeyDto>} [body] Array of blacklistsKeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2BlacklistSearchPost: async (body?: Array<BlacklistKeyDto>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/blacklist/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basicAuth required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlacklistApi - functional programming interface
 * @export
 */
export const BlacklistApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Remove blacklist record by id.
         * @summary Remove the specified resource from storage.
         * @param {string} id Unique identifier of the resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2BlacklistIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BlacklistApiAxiosParamCreator(configuration).v2BlacklistIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Bulk find in blacklist table and return matching entries by the unique blacklist key.
         * @param {Array<BlacklistKeyDto>} [body] Array of blacklistsKeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2BlacklistSearchPost(body?: Array<BlacklistKeyDto>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<BlacklistDto>>>> {
            const localVarAxiosArgs = await BlacklistApiAxiosParamCreator(configuration).v2BlacklistSearchPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BlacklistApi - factory interface
 * @export
 */
export const BlacklistApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Remove blacklist record by id.
         * @summary Remove the specified resource from storage.
         * @param {string} id Unique identifier of the resource.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2BlacklistIdDelete(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BlacklistApiFp(configuration).v2BlacklistIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Bulk find in blacklist table and return matching entries by the unique blacklist key.
         * @param {Array<BlacklistKeyDto>} [body] Array of blacklistsKeys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2BlacklistSearchPost(body?: Array<BlacklistKeyDto>, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<BlacklistDto>>> {
            return BlacklistApiFp(configuration).v2BlacklistSearchPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlacklistApi - object-oriented interface
 * @export
 * @class BlacklistApi
 * @extends {BaseAPI}
 */
export class BlacklistApi extends BaseAPI {
    /**
     * Remove blacklist record by id.
     * @summary Remove the specified resource from storage.
     * @param {string} id Unique identifier of the resource.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlacklistApi
     */
    public async v2BlacklistIdDelete(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BlacklistApiFp(this.configuration).v2BlacklistIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Bulk find in blacklist table and return matching entries by the unique blacklist key.
     * @param {Array<BlacklistKeyDto>} [body] Array of blacklistsKeys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlacklistApi
     */
    public async v2BlacklistSearchPost(body?: Array<BlacklistKeyDto>, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<BlacklistDto>>> {
        return BlacklistApiFp(this.configuration).v2BlacklistSearchPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
