/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Dto model module.
 * @module model/Dto
 * @version 0.0.1
 */
export class Dto {
  /**
   * Constructs a new <code>Dto</code>.
   * @alias module:model/Dto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Dto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Dto} obj Optional instance to populate.
   * @return {module:model/Dto} The populated <code>Dto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Dto();
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} code
 */
Dto.prototype.code = undefined;

/**
 * @member {String} name
 */
Dto.prototype.name = undefined;

/**
 * @member {String} description
 */
Dto.prototype.description = undefined;

