/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PageMetaDto} from './PageMetaDto';
import {VenueDto} from './VenueDto';

/**
 * The VenuePageDto model module.
 * @module model/VenuePageDto
 * @version 0.0.1
 */
export class VenuePageDto {
  /**
   * Constructs a new <code>VenuePageDto</code>.
   * @alias module:model/VenuePageDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>VenuePageDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VenuePageDto} obj Optional instance to populate.
   * @return {module:model/VenuePageDto} The populated <code>VenuePageDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new VenuePageDto();
      if (data.hasOwnProperty('venues'))
        obj.venues = ApiClient.convertToType(data['venues'], [VenueDto]);
      if (data.hasOwnProperty('page_meta'))
        obj.pageMeta = PageMetaDto.constructFromObject(data['page_meta']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/VenueDto>} venues
 */
VenuePageDto.prototype.venues = undefined;

/**
 * @member {module:model/PageMetaDto} pageMeta
 */
VenuePageDto.prototype.pageMeta = undefined;

