/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2TeamScore } from './v2TeamScore';


export interface V2MatchScore { 
    total?: V2TeamScore;
    halfTime?: V2TeamScore;
    regularTime?: V2TeamScore;
    extraTime?: V2TeamScore;
    penaltyShootout?: V2TeamScore;
    aggregate?: V2TeamScore;
}
