/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CityDto,
    CityDtoFromJSON,
    CityDtoFromJSONTyped,
    CityDtoToJSON,
} from './CityDto';
import {
    CountryDto,
    CountryDtoFromJSON,
    CountryDtoFromJSONTyped,
    CountryDtoToJSON,
} from './CountryDto';

/**
 * 
 * @export
 * @interface ListVenueDto
 */
export interface ListVenueDto {
    /**
     * 
     * @type {string}
     * @memberof ListVenueDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ListVenueDto
     */
    name?: string;
    /**
     * 
     * @type {CountryDto}
     * @memberof ListVenueDto
     */
    country?: CountryDto;
    /**
     * 
     * @type {CityDto}
     * @memberof ListVenueDto
     */
    city?: CityDto;
    /**
     * 
     * @type {object}
     * @memberof ListVenueDto
     */
    profile?: object;
}

export function ListVenueDtoFromJSON(json: any): ListVenueDto {
    return ListVenueDtoFromJSONTyped(json, false);
}

export function ListVenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVenueDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'country': !exists(json, 'country') ? undefined : CountryDtoFromJSON(json['country']),
        'city': !exists(json, 'city') ? undefined : CityDtoFromJSON(json['city']),
        'profile': !exists(json, 'profile') ? undefined : json['profile'],
    };
}

export function ListVenueDtoToJSON(value?: ListVenueDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'country': CountryDtoToJSON(value.country),
        'city': CityDtoToJSON(value.city),
        'profile': value.profile,
    };
}

