/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PartialTeam,
    PartialTeamFromJSON,
    PartialTeamFromJSONTyped,
    PartialTeamToJSON,
} from './PartialTeam';
import {
    PlayerTeamAllOf,
    PlayerTeamAllOfFromJSON,
    PlayerTeamAllOfFromJSONTyped,
    PlayerTeamAllOfToJSON,
} from './PlayerTeamAllOf';
import {
    TeamPlayerData,
    TeamPlayerDataFromJSON,
    TeamPlayerDataFromJSONTyped,
    TeamPlayerDataToJSON,
} from './TeamPlayerData';

/**
 * 
 * @export
 * @interface PlayerTeam
 */
export interface PlayerTeam {
    /**
     * Whether the person is currently part of the Team
     * @type {boolean}
     * @memberof PlayerTeam
     */
    active?: boolean;
    /**
     * Date when the Person joined the team
     * @type {Date}
     * @memberof PlayerTeam
     */
    startDate?: Date;
    /**
     * Date when the Person left the team (if any)
     * @type {Date}
     * @memberof PlayerTeam
     */
    endDate?: Date;
    /**
     * Shirt number which the player wears for the team
     * @type {number}
     * @memberof PlayerTeam
     */
    shirtNumber?: number;
    /**
     * Whether the player is on loan with the team
     * @type {boolean}
     * @memberof PlayerTeam
     */
    loan?: boolean;
    /**
     * 
     * @type {PartialTeam}
     * @memberof PlayerTeam
     */
    team: PartialTeam;
}

export function PlayerTeamFromJSON(json: any): PlayerTeam {
    return PlayerTeamFromJSONTyped(json, false);
}

export function PlayerTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerTeam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'startDate': !exists(json, 'start_date') ? undefined : (new Date(json['start_date'])),
        'endDate': !exists(json, 'end_date') ? undefined : (new Date(json['end_date'])),
        'shirtNumber': !exists(json, 'shirt_number') ? undefined : json['shirt_number'],
        'loan': !exists(json, 'loan') ? undefined : json['loan'],
        'team': PartialTeamFromJSON(json['team']),
    };
}

export function PlayerTeamToJSON(value?: PlayerTeam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'start_date': value.startDate === undefined ? undefined : (value.startDate.toISOString().substr(0,10)),
        'end_date': value.endDate === undefined ? undefined : (value.endDate.toISOString().substr(0,10)),
        'shirt_number': value.shirtNumber,
        'loan': value.loan,
        'team': PartialTeamToJSON(value.team),
    };
}

