/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlayerStatisticItem
 */
export interface PlayerStatisticItem {
    /**
     * 
     * @type {string}
     * @memberof PlayerStatisticItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerStatisticItem
     */
    value?: string;
}

export function PlayerStatisticItemFromJSON(json: any): PlayerStatisticItem {
    return PlayerStatisticItemFromJSONTyped(json, false);
}

export function PlayerStatisticItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerStatisticItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function PlayerStatisticItemToJSON(value?: PlayerStatisticItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

