/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2LineupPlayerInput,
    V2LineupPlayerInputFromJSON,
    V2LineupPlayerInputFromJSONTyped,
    V2LineupPlayerInputToJSON,
} from './V2LineupPlayerInput';

/**
 * 
 * @export
 * @interface V2LineupTeamInput
 */
export interface V2LineupTeamInput {
    /**
     * 
     * @type {string}
     * @memberof V2LineupTeamInput
     */
    formation?: string;
    /**
     * 
     * @type {string}
     * @memberof V2LineupTeamInput
     */
    coachId?: string;
    /**
     * 
     * @type {Array<V2LineupPlayerInput>}
     * @memberof V2LineupTeamInput
     */
    players?: Array<V2LineupPlayerInput>;
}

export function V2LineupTeamInputFromJSON(json: any): V2LineupTeamInput {
    return V2LineupTeamInputFromJSONTyped(json, false);
}

export function V2LineupTeamInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2LineupTeamInput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'formation': !exists(json, 'formation') ? undefined : json['formation'],
        'coachId': !exists(json, 'coach_id') ? undefined : json['coach_id'],
        'players': !exists(json, 'players') ? undefined : ((json['players'] as Array<any>).map(V2LineupPlayerInputFromJSON)),
    };
}

export function V2LineupTeamInputToJSON(value?: V2LineupTeamInput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'formation': value.formation,
        'coach_id': value.coachId,
        'players': value.players === undefined ? undefined : ((value.players as Array<any>).map(V2LineupPlayerInputToJSON)),
    };
}

