/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2MappingRequestDto,
    V2MappingRequestDtoFromJSON,
    V2MappingRequestDtoFromJSONTyped,
    V2MappingRequestDtoToJSON,
} from './V2MappingRequestDto';

/**
 * 
 * @export
 * @interface V2MappingRequestsDto
 */
export interface V2MappingRequestsDto {
    /**
     * 
     * @type {string}
     * @memberof V2MappingRequestsDto
     */
    provider?: string;
    /**
     * 
     * @type {Array<V2MappingRequestDto>}
     * @memberof V2MappingRequestsDto
     */
    mappingRequests: Array<V2MappingRequestDto>;
}

export function V2MappingRequestsDtoFromJSON(json: any): V2MappingRequestsDto {
    return V2MappingRequestsDtoFromJSONTyped(json, false);
}

export function V2MappingRequestsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2MappingRequestsDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'mappingRequests': ((json['mapping_requests'] as Array<any>).map(V2MappingRequestDtoFromJSON)),
    };
}

export function V2MappingRequestsDtoToJSON(value?: V2MappingRequestsDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'provider': value.provider,
        'mapping_requests': ((value.mappingRequests as Array<any>).map(V2MappingRequestDtoToJSON)),
    };
}

