/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V2SeasonStage
 */
export interface V2SeasonStage {
    /**
     * 
     * @type {string}
     * @memberof V2SeasonStage
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V2SeasonStage
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V2SeasonStage
     */
    type?: V2SeasonStageTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof V2SeasonStage
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V2SeasonStage
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof V2SeasonStage
     */
    orderInSeason?: number;
    /**
     * 
     * @type {string}
     * @memberof V2SeasonStage
     */
    coverage?: string;
}


/**
 * @export
 */
export const V2SeasonStageTypeEnum = {
    Group: 'GROUP',
    League: 'LEAGUE',
    KnockOut: 'KNOCK_OUT'
} as const;
export type V2SeasonStageTypeEnum = typeof V2SeasonStageTypeEnum[keyof typeof V2SeasonStageTypeEnum];


export function V2SeasonStageFromJSON(json: any): V2SeasonStage {
    return V2SeasonStageFromJSONTyped(json, false);
}

export function V2SeasonStageFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2SeasonStage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'startDate': !exists(json, 'start_date') ? undefined : (new Date(json['start_date'])),
        'endDate': !exists(json, 'end_date') ? undefined : (new Date(json['end_date'])),
        'orderInSeason': !exists(json, 'order_in_season') ? undefined : json['order_in_season'],
        'coverage': !exists(json, 'coverage') ? undefined : json['coverage'],
    };
}

export function V2SeasonStageToJSON(value?: V2SeasonStage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'start_date': value.startDate === undefined ? undefined : (value.startDate.toISOString().substr(0,10)),
        'end_date': value.endDate === undefined ? undefined : (value.endDate.toISOString().substr(0,10)),
        'order_in_season': value.orderInSeason,
        'coverage': value.coverage,
    };
}

