/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2SquadPlayer,
    V2SquadPlayerFromJSON,
    V2SquadPlayerFromJSONTyped,
    V2SquadPlayerToJSON,
} from './V2SquadPlayer';
import {
    V2Team,
    V2TeamFromJSON,
    V2TeamFromJSONTyped,
    V2TeamToJSON,
} from './V2Team';

/**
 * 
 * @export
 * @interface V2TeamSquad
 */
export interface V2TeamSquad {
    /**
     * 
     * @type {V2Team}
     * @memberof V2TeamSquad
     */
    team: V2Team;
    /**
     * 
     * @type {Array<V2SquadPlayer>}
     * @memberof V2TeamSquad
     */
    players: Array<V2SquadPlayer>;
}

export function V2TeamSquadFromJSON(json: any): V2TeamSquad {
    return V2TeamSquadFromJSONTyped(json, false);
}

export function V2TeamSquadFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2TeamSquad {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'team': V2TeamFromJSON(json['team']),
        'players': ((json['players'] as Array<any>).map(V2SquadPlayerFromJSON)),
    };
}

export function V2TeamSquadToJSON(value?: V2TeamSquad | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'team': V2TeamToJSON(value.team),
        'players': ((value.players as Array<any>).map(V2SquadPlayerToJSON)),
    };
}

