/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    V2City,
    V2CityFromJSON,
    V2CityFromJSONTyped,
    V2CityToJSON,
} from './V2City';
import {
    V2Country,
    V2CountryFromJSON,
    V2CountryFromJSONTyped,
    V2CountryToJSON,
} from './V2Country';
import {
    VenueProfileDto,
    VenueProfileDtoFromJSON,
    VenueProfileDtoFromJSONTyped,
    VenueProfileDtoToJSON,
} from './VenueProfileDto';

/**
 * 
 * @export
 * @interface V2VenuesPut
 */
export interface V2VenuesPut {
    /**
     * 
     * @type {string}
     * @memberof V2VenuesPut
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V2VenuesPut
     */
    name: string;
    /**
     * 
     * @type {V2Country}
     * @memberof V2VenuesPut
     */
    country: V2Country;
    /**
     * 
     * @type {V2City}
     * @memberof V2VenuesPut
     */
    city?: V2City;
    /**
     * 
     * @type {VenueProfileDto}
     * @memberof V2VenuesPut
     */
    profile?: VenueProfileDto;
}

export function V2VenuesPutFromJSON(json: any): V2VenuesPut {
    return V2VenuesPutFromJSONTyped(json, false);
}

export function V2VenuesPutFromJSONTyped(json: any, ignoreDiscriminator: boolean): V2VenuesPut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'country': V2CountryFromJSON(json['country']),
        'city': !exists(json, 'city') ? undefined : V2CityFromJSON(json['city']),
        'profile': !exists(json, 'profile') ? undefined : VenueProfileDtoFromJSON(json['profile']),
    };
}

export function V2VenuesPutToJSON(value?: V2VenuesPut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'country': V2CountryToJSON(value.country),
        'city': V2CityToJSON(value.city),
        'profile': VenueProfileDtoToJSON(value.profile),
    };
}

