/**
 * Content-API
 * SMP Content-API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MainMedia } from './MainMedia';
import { Seo } from './Seo';
import { HttpFile } from '../http/http';

export class CategoryRequest {
    /**
    * The title of the content. It should always be provided
    */
    'title'?: string;
    'description'?: string;
    'active'?: boolean;
    'parentId'?: string;
    /**
    * Used to achieve ordering of categories. The current category will be placed after the element with previous_id
    */
    'previousId'?: string;
    /**
    * JSON field with no validation. Should be used for migrated/unsupported content that is no longer needed but needs to be available for legacy reasons.
    */
    'generic'?: any;
    'seo'?: Seo;
    'mainMedia'?: Array<MainMedia>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousId",
            "baseName": "previous_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "generic",
            "baseName": "generic",
            "type": "any",
            "format": ""
        },
        {
            "name": "seo",
            "baseName": "seo",
            "type": "Seo",
            "format": ""
        },
        {
            "name": "mainMedia",
            "baseName": "main_media",
            "type": "Array<MainMedia>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CategoryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

