/**
 * Content-API
 * SMP Content-API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IdMappingCollection } from './IdMappingCollection';
import { HttpFile } from '../http/http';

export class MappingsDelete200Response {
    'data'?: IdMappingCollection;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "IdMappingCollection",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MappingsDelete200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

