/**
 * Content-API
 * SMP Content-API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoFile } from './VideoFile';
import { HttpFile } from '../http/http';

/**
* An object containing various URLs specific for video entities
*/
export class VideoUrls {
    /**
    * An array containing video files
    */
    'videoFiles'?: Array<VideoFile>;
    /**
    * URL to be used for live steaming of video.
    */
    'liveUrl'?: string;
    /**
    * A URL that is going to be used for redirects. If you want a piece of content to take you to a specific page, you should put that address here.
    */
    'externalUrl'?: string;
    /**
    * A URL that is the master in case of duplicate content. Mostly used for SEO purposes.
    */
    'canonicalUrl'?: string;
    /**
    * A URL describing the public location of the resource, when accessed from desktop. Can be used in combination with 3rd party Social Media plugins to achieve Share functionality.
    */
    'publicUrlDesktop'?: string;
    /**
    * A URL describing the public location of the resource, when accessed from mobile.
    */
    'publicUrlMobile'?: string;
    /**
    * A URL describing the public location of the resource, when accessed as Accellerated Mobile Page.
    */
    'publicUrlAmp'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "videoFiles",
            "baseName": "video_files",
            "type": "Array<VideoFile>",
            "format": ""
        },
        {
            "name": "liveUrl",
            "baseName": "live_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUrl",
            "baseName": "external_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "canonicalUrl",
            "baseName": "canonical_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicUrlDesktop",
            "baseName": "public_url_desktop",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicUrlMobile",
            "baseName": "public_url_mobile",
            "type": "string",
            "format": ""
        },
        {
            "name": "publicUrlAmp",
            "baseName": "public_url_amp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoUrls.attributeTypeMap;
    }

    public constructor() {
    }
}

