/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2LineupTeamDto } from './v2LineupTeamDto';


export interface V2Lineup { 
    matchId?: string;
    status?: V2Lineup.StatusEnum;
    homeTeam?: V2LineupTeamDto;
    awayTeam?: V2LineupTeamDto;
}
export namespace V2Lineup {
    export type StatusEnum = 'CONFIRMED' | 'UNCONFIRMED' | 'NOT_AVAILABLE';
    export const StatusEnum = {
        CONFIRMED: 'CONFIRMED' as StatusEnum,
        UNCONFIRMED: 'UNCONFIRMED' as StatusEnum,
        NOTAVAILABLE: 'NOT_AVAILABLE' as StatusEnum
    }
}
