/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/toPromise';
import IHttpClient from '../IHttpClient';
import { inject, injectable } from 'inversify';
import { IAPIConfiguration } from '../IAPIConfiguration';
import { Headers } from '../Headers';
import HttpResponse from '../HttpResponse';

import { V2RoundTypes } from '../model/v2RoundTypes';

import { COLLECTION_FORMATS }  from '../variables';



@injectable()
export class RoundsService {
    @inject('IAPIConfiguration') private APIConfiguration: IAPIConfiguration;
    @inject('IApiHttpClient') private httpClient: IHttpClient;



    /**
     * 
     * Get a list of rounds per season
     * @param seasonId Filter round types per a season ID
     * @param languageCode Returns translated response based on the language code
     
     */
    public v2RoundsGet(seasonId: number, languageCode?: string, observe?: 'body', headers?: Headers): Observable<V2RoundTypes>;
    public v2RoundsGet(seasonId: number, languageCode?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<V2RoundTypes>>;
    public v2RoundsGet(seasonId: number, languageCode?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!seasonId){
            throw new Error('Required parameter seasonId was null or undefined when calling v2RoundsGet.');
        }

        let queryParameters: string[] = [];
        if (seasonId !== undefined) {
            queryParameters.push('seasonId='+encodeURIComponent(String(seasonId)));
        }
        if (languageCode !== undefined) {
            queryParameters.push('languageCode='+encodeURIComponent(String(languageCode)));
        }

        // authentication (basicAuth) required
        if (this.APIConfiguration.username || this.APIConfiguration.password) {
            headers['Authorization'] = btoa(this.APIConfiguration.username + ':' + this.APIConfiguration.password);
        }
        headers['Accept'] = 'application/json; charset=utf-8';

        const response: Observable<HttpResponse<V2RoundTypes>> = this.httpClient.get(`${this.APIConfiguration.basePath}/v2/rounds?${queryParameters.join('&')}` as any, headers);
        if (observe === 'body') {
               return response.map(httpResponse => httpResponse.response);
        }
        return response;
    }


    /**
     * 
     * Get a list of rounds per stage
     * @param id Unique identifier of the resource.
     * @param languageCode Returns translated response based on the language code
     
     */
    public v2StagesIdRoundsGet(id: string, languageCode?: string, observe?: 'body', headers?: Headers): Observable<V2RoundTypes>;
    public v2StagesIdRoundsGet(id: string, languageCode?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<V2RoundTypes>>;
    public v2StagesIdRoundsGet(id: string, languageCode?: string, observe: any = 'body', headers: Headers = {}): Observable<any> {
        if (!id){
            throw new Error('Required parameter id was null or undefined when calling v2StagesIdRoundsGet.');
        }

        let queryParameters: string[] = [];
        if (languageCode !== undefined) {
            queryParameters.push('languageCode='+encodeURIComponent(String(languageCode)));
        }

        // authentication (basicAuth) required
        if (this.APIConfiguration.username || this.APIConfiguration.password) {
            headers['Authorization'] = btoa(this.APIConfiguration.username + ':' + this.APIConfiguration.password);
        }
        headers['Accept'] = 'application/json; charset=utf-8';

        const response: Observable<HttpResponse<V2RoundTypes>> = this.httpClient.get(`${this.APIConfiguration.basePath}/v2/stages/${encodeURIComponent(String(id))}/rounds?${queryParameters.join('&')}` as any, headers);
        if (observe === 'body') {
               return response.map(httpResponse => httpResponse.response);
        }
        return response;
    }

}
