/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PartialTeam} from './PartialTeam';
import {StandingRule} from './StandingRule';

/**
 * The StandingData model module.
 * @module model/StandingData
 * @version 0.0.1
 */
export class StandingData {
  /**
   * Constructs a new <code>StandingData</code>.
   * @alias module:model/StandingData
   * @class
   * @param rank {Number} Position of the team/player in the standing
   * @param team {module:model/PartialTeam} 
   */
  constructor(rank, team) {
    this.rank = rank;
    this.team = team;
  }

  /**
   * Constructs a <code>StandingData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StandingData} obj Optional instance to populate.
   * @return {module:model/StandingData} The populated <code>StandingData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StandingData();
      if (data.hasOwnProperty('rank'))
        obj.rank = ApiClient.convertToType(data['rank'], 'Number');
      if (data.hasOwnProperty('team'))
        obj.team = PartialTeam.constructFromObject(data['team']);
      if (data.hasOwnProperty('rules'))
        obj.rules = ApiClient.convertToType(data['rules'], [StandingRule]);
    }
    return obj;
  }
}

/**
 * Position of the team/player in the standing
 * @member {Number} rank
 */
StandingData.prototype.rank = undefined;

/**
 * @member {module:model/PartialTeam} team
 */
StandingData.prototype.team = undefined;

/**
 * List of applicable rules to the current standing rank
 * @member {Array.<module:model/StandingRule>} rules
 */
StandingData.prototype.rules = undefined;

