/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TeamSocialDto model module.
 * @module model/TeamSocialDto
 * @version 0.0.1
 */
export class TeamSocialDto {
  /**
   * Constructs a new <code>TeamSocialDto</code>.
   * @alias module:model/TeamSocialDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TeamSocialDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamSocialDto} obj Optional instance to populate.
   * @return {module:model/TeamSocialDto} The populated <code>TeamSocialDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamSocialDto();
      if (data.hasOwnProperty('web'))
        obj.web = ApiClient.convertToType(data['web'], 'String');
      if (data.hasOwnProperty('twitter_id'))
        obj.twitterId = ApiClient.convertToType(data['twitter_id'], 'String');
      if (data.hasOwnProperty('facebook_id'))
        obj.facebookId = ApiClient.convertToType(data['facebook_id'], 'String');
      if (data.hasOwnProperty('instagram_id'))
        obj.instagramId = ApiClient.convertToType(data['instagram_id'], 'String');
      if (data.hasOwnProperty('wikipedia_id'))
        obj.wikipediaId = ApiClient.convertToType(data['wikipedia_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} web
 */
TeamSocialDto.prototype.web = undefined;

/**
 * @member {String} twitterId
 */
TeamSocialDto.prototype.twitterId = undefined;

/**
 * @member {String} facebookId
 */
TeamSocialDto.prototype.facebookId = undefined;

/**
 * @member {String} instagramId
 */
TeamSocialDto.prototype.instagramId = undefined;

/**
 * @member {String} wikipediaId
 */
TeamSocialDto.prototype.wikipediaId = undefined;

