/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {BasicPlayerStats} from './BasicPlayerStats';
import {TournamentSeasonStage} from './TournamentSeasonStage';

/**
 * The TeamSeasonStatistics model module.
 * @module model/TeamSeasonStatistics
 * @version 0.0.1
 */
export class TeamSeasonStatistics {
  /**
   * Constructs a new <code>TeamSeasonStatistics</code>.
   * @alias module:model/TeamSeasonStatistics
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TeamSeasonStatistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TeamSeasonStatistics} obj Optional instance to populate.
   * @return {module:model/TeamSeasonStatistics} The populated <code>TeamSeasonStatistics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TeamSeasonStatistics();
      if (data.hasOwnProperty('team_id'))
        obj.teamId = ApiClient.convertToType(data['team_id'], 'Number');
      if (data.hasOwnProperty('latest_league_stage'))
        obj.latestLeagueStage = TournamentSeasonStage.constructFromObject(data['latest_league_stage']);
      if (data.hasOwnProperty('player_statistics'))
        obj.playerStatistics = ApiClient.convertToType(data['player_statistics'], [BasicPlayerStats]);
    }
    return obj;
  }
}

/**
 * @member {Number} teamId
 */
TeamSeasonStatistics.prototype.teamId = undefined;

/**
 * @member {module:model/TournamentSeasonStage} latestLeagueStage
 */
TeamSeasonStatistics.prototype.latestLeagueStage = undefined;

/**
 * Player statistics for the TournamentSeason
 * @member {Array.<module:model/BasicPlayerStats>} playerStatistics
 */
TeamSeasonStatistics.prototype.playerStatistics = undefined;

