/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TournamentItemDto model module.
 * @module model/TournamentItemDto
 * @version 0.0.1
 */
export class TournamentItemDto {
  /**
   * Constructs a new <code>TournamentItemDto</code>.
   * @alias module:model/TournamentItemDto
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TournamentItemDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TournamentItemDto} obj Optional instance to populate.
   * @return {module:model/TournamentItemDto} The populated <code>TournamentItemDto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TournamentItemDto();
      if (data.hasOwnProperty('tournament_id'))
        obj.tournamentId = ApiClient.convertToType(data['tournament_id'], 'String');
      if (data.hasOwnProperty('sort_order'))
        obj.sortOrder = ApiClient.convertToType(data['sort_order'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} tournamentId
 */
TournamentItemDto.prototype.tournamentId = undefined;

/**
 * @member {Number} sortOrder
 */
TournamentItemDto.prototype.sortOrder = undefined;

