/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {V2MatchScore} from './V2MatchScore';

/**
 * The V2KnockoutMatch model module.
 * @module model/V2KnockoutMatch
 * @version 0.0.1
 */
export class V2KnockoutMatch {
  /**
   * Constructs a new <code>V2KnockoutMatch</code>.
   * @alias module:model/V2KnockoutMatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V2KnockoutMatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V2KnockoutMatch} obj Optional instance to populate.
   * @return {module:model/V2KnockoutMatch} The populated <code>V2KnockoutMatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V2KnockoutMatch();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('kickoff_time'))
        obj.kickoffTime = ApiClient.convertToType(data['kickoff_time'], 'Date');
      if (data.hasOwnProperty('score'))
        obj.score = V2MatchScore.constructFromObject(data['score']);
      if (data.hasOwnProperty('home_team_id'))
        obj.homeTeamId = ApiClient.convertToType(data['home_team_id'], 'String');
      if (data.hasOwnProperty('away_team_id'))
        obj.awayTeamId = ApiClient.convertToType(data['away_team_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
V2KnockoutMatch.prototype.id = undefined;

/**
 * @member {Date} kickoffTime
 */
V2KnockoutMatch.prototype.kickoffTime = undefined;

/**
 * @member {module:model/V2MatchScore} score
 */
V2KnockoutMatch.prototype.score = undefined;

/**
 * @member {String} homeTeamId
 */
V2KnockoutMatch.prototype.homeTeamId = undefined;

/**
 * @member {String} awayTeamId
 */
V2KnockoutMatch.prototype.awayTeamId = undefined;

