/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Country } from './Country';
import { HttpFile } from '../http/http';

export class PartialTournamentSeasonStage {
    /**
    * Unique identifier
    */
    'id': number;
    /**
    * Human readable name of the TournamentSeasonStage
    */
    'name': string;
    /**
    * Whether the stage is a cup such as Champions League Knockout stage, World Cup Final stages, etc
    */
    'cup': boolean;
    /**
    * Id of the TournamentSeason in which the stage is part of
    */
    'tournamentSeasonId': number;
    /**
    * Id of the Tournament in whicth the stage is part of
    */
    'tournamentId': number;
    'country': Country;
    /**
    * Indicates which confederation the stage is part of (for World Cup qualif.)
    */
    'confederation'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "cup",
            "baseName": "cup",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tournamentSeasonId",
            "baseName": "tournament_season_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "tournamentId",
            "baseName": "tournament_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "Country",
            "format": ""
        },
        {
            "name": "confederation",
            "baseName": "confederation",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PartialTournamentSeasonStage.attributeTypeMap;
    }

    public constructor() {
    }
}

