/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2Player } from './V2Player';
import { V2TeamScore } from './V2TeamScore';
import { HttpFile } from '../http/http';

export class V2MatchEvent {
    'id'?: string;
    'matchId'?: string;
    'typeCode'?: V2MatchEventTypeCodeEnum;
    'teamPosition'?: V2MatchEventTeamPositionEnum;
    'minute'?: number;
    'teamId'?: string;
    'primaryPlayer'?: V2Player;
    'secondaryPlayer'?: V2Player;
    'score'?: V2TeamScore;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchId",
            "baseName": "match_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "type_code",
            "type": "V2MatchEventTypeCodeEnum",
            "format": ""
        },
        {
            "name": "teamPosition",
            "baseName": "team_position",
            "type": "V2MatchEventTeamPositionEnum",
            "format": ""
        },
        {
            "name": "minute",
            "baseName": "minute",
            "type": "number",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "primaryPlayer",
            "baseName": "primary_player",
            "type": "V2Player",
            "format": ""
        },
        {
            "name": "secondaryPlayer",
            "baseName": "secondary_player",
            "type": "V2Player",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "V2TeamScore",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2MatchEvent.attributeTypeMap;
    }

    public constructor() {
    }
}


export type V2MatchEventTypeCodeEnum = "YELLOW_RED_CARD" | "PENALTY_SHOOTOUT_MISSED" | "PENALTY_SHOOTOUT_SCORED" | "SUBSTITUTION" | "GOAL" | "RED_CARD" | "PENALTY_MISS" | "YELLOW_CARD" | "ASSIST" | "PENALTY_GOAL" | "OWN_GOAL" ;
export type V2MatchEventTeamPositionEnum = "HOME" | "AWAY" ;

