/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V2PlayerStatisticOutput {
    'playerId'?: string;
    'matchId'?: string;
    'teamId'?: string;
    'statistics'?: any;
    'origin'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerId",
            "baseName": "player_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchId",
            "baseName": "match_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "any",
            "format": ""
        },
        {
            "name": "origin",
            "baseName": "origin",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2PlayerStatisticOutput.attributeTypeMap;
    }

    public constructor() {
    }
}

