/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2TournamentItemOutput } from './v2-tournament-item-output';
/**
 * 
 * @export
 * @interface V2TournamentGroupGetOutput
 */
export interface V2TournamentGroupGetOutput {
    /**
     * 
     * @type {string}
     * @memberof V2TournamentGroupGetOutput
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TournamentGroupGetOutput
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TournamentGroupGetOutput
     */
    description?: string;
    /**
     * 
     * @type {Array<V2TournamentItemOutput>}
     * @memberof V2TournamentGroupGetOutput
     */
    tournaments?: Array<V2TournamentItemOutput>;
}
