/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FootballApi);
  }
}(this, function(expect, FootballApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PlayerStatistics', function() {
      beforeEach(function() {
        instance = new FootballApi.PlayerStatistics();
      });

      it('should create an instance of PlayerStatistics', function() {
        // TODO: update the code to test PlayerStatistics
        expect(instance).to.be.a(FootballApi.PlayerStatistics);
      });

      it('should have the property tournamentSeason (base name: "tournament_season")', function() {
        // TODO: update the code to test the property tournamentSeason
        expect(instance).to.have.property('tournamentSeason');
        // expect(instance.tournamentSeason).to.be(expectedValueLiteral);
      });

      it('should have the property player (base name: "player")', function() {
        // TODO: update the code to test the property player
        expect(instance).to.have.property('player');
        // expect(instance.player).to.be(expectedValueLiteral);
      });

      it('should have the property team (base name: "team")', function() {
        // TODO: update the code to test the property team
        expect(instance).to.have.property('team');
        // expect(instance.team).to.be(expectedValueLiteral);
      });

      it('should have the property shirtNumber (base name: "shirtNumber")', function() {
        // TODO: update the code to test the property shirtNumber
        expect(instance).to.have.property('shirtNumber');
        // expect(instance.shirtNumber).to.be(expectedValueLiteral);
      });

      it('should have the property position (base name: "position")', function() {
        // TODO: update the code to test the property position
        expect(instance).to.have.property('position');
        // expect(instance.position).to.be(expectedValueLiteral);
      });

    });
  });

}));
