/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FootballApi);
  }
}(this, function(expect, FootballApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('V2LineupTeamInput', function() {
      beforeEach(function() {
        instance = new FootballApi.V2LineupTeamInput();
      });

      it('should create an instance of V2LineupTeamInput', function() {
        // TODO: update the code to test V2LineupTeamInput
        expect(instance).to.be.a(FootballApi.V2LineupTeamInput);
      });

      it('should have the property formation (base name: "formation")', function() {
        // TODO: update the code to test the property formation
        expect(instance).to.have.property('formation');
        // expect(instance.formation).to.be(expectedValueLiteral);
      });

      it('should have the property coachId (base name: "coach_id")', function() {
        // TODO: update the code to test the property coachId
        expect(instance).to.have.property('coachId');
        // expect(instance.coachId).to.be(expectedValueLiteral);
      });

      it('should have the property players (base name: "players")', function() {
        // TODO: update the code to test the property players
        expect(instance).to.have.property('players');
        // expect(instance.players).to.be(expectedValueLiteral);
      });

    });
  });

}));
