/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FootballApi);
  }
}(this, function(expect, FootballApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('V2MatchEventInput', function() {
      beforeEach(function() {
        instance = new FootballApi.V2MatchEventInput();
      });

      it('should create an instance of V2MatchEventInput', function() {
        // TODO: update the code to test V2MatchEventInput
        expect(instance).to.be.a(FootballApi.V2MatchEventInput);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property typeCode (base name: "type_code")', function() {
        // TODO: update the code to test the property typeCode
        expect(instance).to.have.property('typeCode');
        // expect(instance.typeCode).to.be(expectedValueLiteral);
      });

      it('should have the property teamPosition (base name: "team_position")', function() {
        // TODO: update the code to test the property teamPosition
        expect(instance).to.have.property('teamPosition');
        // expect(instance.teamPosition).to.be(expectedValueLiteral);
      });

      it('should have the property minute (base name: "minute")', function() {
        // TODO: update the code to test the property minute
        expect(instance).to.have.property('minute');
        // expect(instance.minute).to.be(expectedValueLiteral);
      });

      it('should have the property primaryPlayerId (base name: "primary_player_id")', function() {
        // TODO: update the code to test the property primaryPlayerId
        expect(instance).to.have.property('primaryPlayerId');
        // expect(instance.primaryPlayerId).to.be(expectedValueLiteral);
      });

      it('should have the property secondaryPlayerId (base name: "secondary_player_id")', function() {
        // TODO: update the code to test the property secondaryPlayerId
        expect(instance).to.have.property('secondaryPlayerId');
        // expect(instance.secondaryPlayerId).to.be(expectedValueLiteral);
      });

      it('should have the property sortOrder (base name: "sort_order")', function() {
        // TODO: update the code to test the property sortOrder
        expect(instance).to.have.property('sortOrder');
        // expect(instance.sortOrder).to.be(expectedValueLiteral);
      });

    });
  });

}));
