/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EventPlayerType
 */
export interface EventPlayerType {
    /**
     * Indicates what part of the lineup the player belongs to
     * @type {string}
     * @memberof EventPlayerType
     */
    category: EventPlayerTypeCategoryEnum;
    /**
     * Human readable name of the type
     * @type {string}
     * @memberof EventPlayerType
     */
    name: string;
    /**
     * Internal unique code to identify the type
     * @type {string}
     * @memberof EventPlayerType
     */
    code: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EventPlayerTypeCategoryEnum {
    Miss = 'miss',
    Sub = 'sub',
    Start = 'start',
    Unknown = 'unknown'
}

