/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerStatsBasic
 */
export interface PlayerStatsBasic {
    /**
     * Total goals scored
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    goals: number;
    /**
     * Total games played
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    played: number;
    /**
     * Total minutes played
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    minutes: number;
    /**
     * Number of red cards
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    redCards: number;
    /**
     * Number of yellow cards
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    yellowCards: number;
    /**
     * Number of assists
     * @type {number}
     * @memberof PlayerStatsBasic
     */
    assists?: number;
}
