/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlayerEditSocialDto
 */
export interface PlayerEditSocialDto {
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    web?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    twitterId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    facebookId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    instagramId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    wikipediaId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlayerEditSocialDto
     */
    youtubeChannelId?: string;
}
