/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RefereeEditDto
 */
export interface RefereeEditDto {
    /**
     * 
     * @type {string}
     * @memberof RefereeEditDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RefereeEditDto
     */
    countryId?: string;
    /**
     * 
     * @type {Date}
     * @memberof RefereeEditDto
     */
    birthdate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof RefereeEditDto
     */
    active?: boolean;
}
