/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { V2Country } from './v2-country';
/**
 * 
 * @export
 * @interface V2City
 */
export interface V2City {
    /**
     * 
     * @type {string}
     * @memberof V2City
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V2City
     */
    name?: string;
    /**
     * 
     * @type {V2Country}
     * @memberof V2City
     */
    country?: V2Country;
}
