/* tslint:disable */
/* eslint-disable */
/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TeamSocialDto } from './team-social-dto';
import { V2Coach } from './v2-coach';
import { V2Country } from './v2-country';
import { V2President } from './v2-president';
import { V2Season } from './v2-season';
import { V2TeamColorsColors } from './v2-team-colors-colors';
import { V2VenuesGetId } from './v2-venues-get-id';
/**
 * 
 * @export
 * @interface V2TeamProfile
 */
export interface V2TeamProfile {
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    threeLetterCode?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    shortName?: string;
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof V2TeamProfile
     */
    founded?: number;
    /**
     * 
     * @type {V2Country}
     * @memberof V2TeamProfile
     */
    country?: V2Country;
    /**
     * 
     * @type {V2VenuesGetId}
     * @memberof V2TeamProfile
     */
    venue?: V2VenuesGetId;
    /**
     * 
     * @type {TeamSocialDto}
     * @memberof V2TeamProfile
     */
    social?: TeamSocialDto;
    /**
     * 
     * @type {V2Coach}
     * @memberof V2TeamProfile
     */
    coach?: V2Coach;
    /**
     * 
     * @type {V2President}
     * @memberof V2TeamProfile
     */
    president?: V2President;
    /**
     * 
     * @type {string}
     * @memberof V2TeamProfile
     */
    gender?: V2TeamProfileGenderEnum;
    /**
     * 
     * @type {Array<V2Season>}
     * @memberof V2TeamProfile
     */
    activeSeasons?: Array<V2Season>;
    /**
     * 
     * @type {Array<V2TeamColorsColors>}
     * @memberof V2TeamProfile
     */
    shirtColors?: Array<V2TeamColorsColors>;
}

/**
    * @export
    * @enum {string}
    */
export enum V2TeamProfileGenderEnum {
    MALE = 'MALE',
    FEMALE = 'FEMALE'
}

