export * from './AssetsApi';
import { AssetsApi } from './AssetsApi';
export * from './BlacklistApi';
import { BlacklistApi } from './BlacklistApi';
export * from './CitiesApi';
import { CitiesApi } from './CitiesApi';
export * from './CoachesApi';
import { CoachesApi } from './CoachesApi';
export * from './CountriesApi';
import { CountriesApi } from './CountriesApi';
export * from './EventIncidentsApi';
import { EventIncidentsApi } from './EventIncidentsApi';
export * from './EventPlayerTypeApi';
import { EventPlayerTypeApi } from './EventPlayerTypeApi';
export * from './EventStatusApi';
import { EventStatusApi } from './EventStatusApi';
export * from './EventsApi';
import { EventsApi } from './EventsApi';
export * from './KnockoutSchemeApi';
import { KnockoutSchemeApi } from './KnockoutSchemeApi';
export * from './LanguagesApi';
import { LanguagesApi } from './LanguagesApi';
export * from './LineupsApi';
import { LineupsApi } from './LineupsApi';
export * from './MappingsApi';
import { MappingsApi } from './MappingsApi';
export * from './MatchEventsApi';
import { MatchEventsApi } from './MatchEventsApi';
export * from './MatchesApi';
import { MatchesApi } from './MatchesApi';
export * from './OddsApi';
import { OddsApi } from './OddsApi';
export * from './PlayerStatisticApi';
import { PlayerStatisticApi } from './PlayerStatisticApi';
export * from './PlayersApi';
import { PlayersApi } from './PlayersApi';
export * from './PresidentsApi';
import { PresidentsApi } from './PresidentsApi';
export * from './ProviderMappingsApi';
import { ProviderMappingsApi } from './ProviderMappingsApi';
export * from './RefereesApi';
import { RefereesApi } from './RefereesApi';
export * from './RoundsApi';
import { RoundsApi } from './RoundsApi';
export * from './SeasonApi';
import { SeasonApi } from './SeasonApi';
export * from './StagesApi';
import { StagesApi } from './StagesApi';
export * from './StandingRuleApi';
import { StandingRuleApi } from './StandingRuleApi';
export * from './StandingsApi';
import { StandingsApi } from './StandingsApi';
export * from './TeamSquadApi';
import { TeamSquadApi } from './TeamSquadApi';
export * from './TeamStatsApi';
import { TeamStatsApi } from './TeamStatsApi';
export * from './TeamsApi';
import { TeamsApi } from './TeamsApi';
export * from './TournamentGroupsApi';
import { TournamentGroupsApi } from './TournamentGroupsApi';
export * from './TournamentsApi';
import { TournamentsApi } from './TournamentsApi';
export * from './TranslationsApi';
import { TranslationsApi } from './TranslationsApi';
export * from './VenuesApi';
import { VenuesApi } from './VenuesApi';
export const APIS = [AssetsApi, BlacklistApi, CitiesApi, CoachesApi, CountriesApi, EventIncidentsApi, EventPlayerTypeApi, EventStatusApi, EventsApi, KnockoutSchemeApi, LanguagesApi, LineupsApi, MappingsApi, MatchEventsApi, MatchesApi, OddsApi, PlayerStatisticApi, PlayersApi, PresidentsApi, ProviderMappingsApi, RefereesApi, RoundsApi, SeasonApi, StagesApi, StandingRuleApi, StandingsApi, TeamSquadApi, TeamStatsApi, TeamsApi, TournamentGroupsApi, TournamentsApi, TranslationsApi, VenuesApi];
