import * as api from './api/api';
import * as angular from 'angular';

const apiModule = angular.module('api', [])
.service('AssetsApi', api.AssetsApi)
.service('BlacklistApi', api.BlacklistApi)
.service('CitiesApi', api.CitiesApi)
.service('CoachesApi', api.CoachesApi)
.service('CountriesApi', api.CountriesApi)
.service('EventIncidentsApi', api.EventIncidentsApi)
.service('EventPlayerTypeApi', api.EventPlayerTypeApi)
.service('EventStatusApi', api.EventStatusApi)
.service('EventsApi', api.EventsApi)
.service('KnockoutSchemeApi', api.KnockoutSchemeApi)
.service('LanguagesApi', api.LanguagesApi)
.service('LineupsApi', api.LineupsApi)
.service('MappingsApi', api.MappingsApi)
.service('MatchEventsApi', api.MatchEventsApi)
.service('MatchesApi', api.MatchesApi)
.service('OddsApi', api.OddsApi)
.service('PlayerStatisticApi', api.PlayerStatisticApi)
.service('PlayersApi', api.PlayersApi)
.service('PresidentsApi', api.PresidentsApi)
.service('ProviderMappingsApi', api.ProviderMappingsApi)
.service('RefereesApi', api.RefereesApi)
.service('RoundsApi', api.RoundsApi)
.service('SeasonApi', api.SeasonApi)
.service('StagesApi', api.StagesApi)
.service('StandingRuleApi', api.StandingRuleApi)
.service('StandingsApi', api.StandingsApi)
.service('TeamSquadApi', api.TeamSquadApi)
.service('TeamStatsApi', api.TeamStatsApi)
.service('TeamsApi', api.TeamsApi)
.service('TournamentGroupsApi', api.TournamentGroupsApi)
.service('TournamentsApi', api.TournamentsApi)
.service('TranslationsApi', api.TranslationsApi)
.service('VenuesApi', api.VenuesApi)

export default apiModule;
