/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CountryDto } from './CountryDto';
import { HttpFile } from '../http/http';

export class CityDto {
    'id'?: string;
    'name'?: string;
    'country'?: CountryDto;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "CountryDto",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CityDto.attributeTypeMap;
    }

    public constructor() {
    }
}

