/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PartialEvent } from './PartialEvent';
import { HttpFile } from '../http/http';

export class Round {
    'round': string;
    'startTime': Date;
    'endTime': Date;
    'events'?: Array<PartialEvent>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "round",
            "baseName": "round",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<PartialEvent>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Round.attributeTypeMap;
    }

    public constructor() {
    }
}

