/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LeagueStandingData } from './LeagueStandingData';
import { HttpFile } from '../http/http';

export class StageGroupWithStandingAllOf {
    /**
    * League Standing for the StageGroup if available and requested
    */
    'standing'?: Array<LeagueStandingData>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "standing",
            "baseName": "standing",
            "type": "Array<LeagueStandingData>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StageGroupWithStandingAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

