/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TeamPlayerData {
    /**
    * Shirt number which the player wears for the team
    */
    'shirtNumber'?: number;
    /**
    * Whether the player is on loan with the team
    */
    'loan'?: boolean;
    /**
    * Whether the person is currently part of the Team
    */
    'active': boolean;
    /**
    * Date when the Person joined the team
    */
    'startDate'?: string;
    /**
    * Date when the Person left the team (if any)
    */
    'endDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shirtNumber",
            "baseName": "shirt_number",
            "type": "number",
            "format": ""
        },
        {
            "name": "loan",
            "baseName": "loan",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return TeamPlayerData.attributeTypeMap;
    }

    public constructor() {
    }
}

