/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V2MappingDto {
    'provider'?: string;
    'entityType'?: V2MappingDtoEntityTypeEnum;
    'domainId'?: string;
    'providerId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "V2MappingDtoEntityTypeEnum",
            "format": ""
        },
        {
            "name": "domainId",
            "baseName": "domain_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerId",
            "baseName": "provider_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2MappingDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export type V2MappingDtoEntityTypeEnum = "PLAYER" | "TEAM" | "COACH" | "MATCH" | "SEASON" | "VENUE" | "REFEREE" | "TOURNAMENT" | "CITY" | "PRESIDENT" | "STAGE" | "GROUP" | "COUNTRY" | "ODD_PROVIDER" ;

