/*
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FootballApi);
  }
}(this, function(expect, FootballApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FootballApi.LineupsApi();
  });

  describe('(package)', function() {
    describe('LineupsApi', function() {
      describe('lineupsGet', function() {
        it('should call lineupsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for lineupsGet call and complete the assertions
          /*
          var opts = {};

          instance.lineupsGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(FootballApi.Lineup);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v2MatchesIdLineupsGet', function() {
        it('should call v2MatchesIdLineupsGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v2MatchesIdLineupsGet call and complete the assertions
          /*
          var opts = {};

          instance.v2MatchesIdLineupsGet(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FootballApi.V2Lineup);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v2MatchesIdLineupsPut', function() {
        it('should call v2MatchesIdLineupsPut successfully', function(done) {
          // TODO: uncomment, update parameter values for v2MatchesIdLineupsPut call and complete the assertions
          /*

          instance.v2MatchesIdLineupsPut(body, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(FootballApi.V2Lineup);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
