export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './blacklist.service';
import { BlacklistService } from './blacklist.service';
export * from './cities.service';
import { CitiesService } from './cities.service';
export * from './coaches.service';
import { CoachesService } from './coaches.service';
export * from './countries.service';
import { CountriesService } from './countries.service';
export * from './eventIncidents.service';
import { EventIncidentsService } from './eventIncidents.service';
export * from './eventPlayerType.service';
import { EventPlayerTypeService } from './eventPlayerType.service';
export * from './eventStatus.service';
import { EventStatusService } from './eventStatus.service';
export * from './events.service';
import { EventsService } from './events.service';
export * from './knockoutScheme.service';
import { KnockoutSchemeService } from './knockoutScheme.service';
export * from './languages.service';
import { LanguagesService } from './languages.service';
export * from './lineups.service';
import { LineupsService } from './lineups.service';
export * from './mappings.service';
import { MappingsService } from './mappings.service';
export * from './matchEvents.service';
import { MatchEventsService } from './matchEvents.service';
export * from './matches.service';
import { MatchesService } from './matches.service';
export * from './odds.service';
import { OddsService } from './odds.service';
export * from './playerStatistic.service';
import { PlayerStatisticService } from './playerStatistic.service';
export * from './players.service';
import { PlayersService } from './players.service';
export * from './presidents.service';
import { PresidentsService } from './presidents.service';
export * from './providerMappings.service';
import { ProviderMappingsService } from './providerMappings.service';
export * from './referees.service';
import { RefereesService } from './referees.service';
export * from './rounds.service';
import { RoundsService } from './rounds.service';
export * from './season.service';
import { SeasonService } from './season.service';
export * from './stages.service';
import { StagesService } from './stages.service';
export * from './standingRule.service';
import { StandingRuleService } from './standingRule.service';
export * from './standings.service';
import { StandingsService } from './standings.service';
export * from './teamSquad.service';
import { TeamSquadService } from './teamSquad.service';
export * from './teamStats.service';
import { TeamStatsService } from './teamStats.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './tournamentGroups.service';
import { TournamentGroupsService } from './tournamentGroups.service';
export * from './tournaments.service';
import { TournamentsService } from './tournaments.service';
export * from './translations.service';
import { TranslationsService } from './translations.service';
export * from './venues.service';
import { VenuesService } from './venues.service';
export const APIS = [AssetsService, BlacklistService, CitiesService, CoachesService, CountriesService, EventIncidentsService, EventPlayerTypeService, EventStatusService, EventsService, KnockoutSchemeService, LanguagesService, LineupsService, MappingsService, MatchEventsService, MatchesService, OddsService, PlayerStatisticService, PlayersService, PresidentsService, ProviderMappingsService, RefereesService, RoundsService, SeasonService, StagesService, StandingRuleService, StandingsService, TeamSquadService, TeamStatsService, TeamsService, TournamentGroupsService, TournamentsService, TranslationsService, VenuesService];
