/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  MappingRequest,
  V2MappingDto,
} from './models';

/**
 * v2MappingsSearchPost - parameters interface
 */
export interface IV2MappingsSearchPostParams {
  mappingRequest?: MappingRequest;
}

/**
 * ProviderMappingsApi - API class
 */
@autoinject()
export class ProviderMappingsApi extends Api {

  /**
   * Creates a new ProviderMappingsApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Bulk find provider to internal ID mappings by their provider ID and entity type.
   * @param params.mappingRequest Data entity provider name and array of mapping requests
   */
  async v2MappingsSearchPost(params: IV2MappingsSearchPostParams): Promise<Array<V2MappingDto>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/v2/mappings/search`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPost()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['mappingRequest'] || {}))

      // Authentication 'basicAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

