/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.TeamSquadApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * API for accessing various kinds of football data, updated in real time.
 * Version: 0.0.1
 * Generated by: io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
 */
goog.provide('API.Client.TeamSquadApi');

goog.require('API.Client.V2TeamSquadInput');
goog.require('API.Client.v2_TeamSquad');

/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.TeamSquadApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('TeamSquadApiBasePath') ?
                   /** @type {!string} */ ($injector.get('TeamSquadApiBasePath')) :
                   'https://false';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('TeamSquadApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('TeamSquadApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.TeamSquadApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * 
 * Get teams squad
 * @param {!string} id Unique identifier of the resource.
 * @param {!string=} opt_memberStatus 
 * @param {!string=} opt_languageCode Returns translated response based on the language code
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.v2_TeamSquad>}
 */
API.Client.TeamSquadApi.prototype.v2TeamsIdSquadGet = function(id, opt_memberStatus, opt_languageCode, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v2/teams/{id}/squad'
      .replace('{' + 'id' + '}', String(id));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'id' is set
  if (!id) {
    throw new Error('Missing required parameter id when calling v2TeamsIdSquadGet');
  }
  if (opt_memberStatus !== undefined) {
    queryParameters['memberStatus'] = opt_memberStatus;
  }

  if (opt_languageCode !== undefined) {
    queryParameters['language_code'] = opt_languageCode;
  }

  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Update TeamSquad members
 * @param {!V2TeamSquadInput} squadMembers TeamSquad members to update. Null value for a property means no update
 * @param {!string} id Unique identifier of the resource.
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.v2_TeamSquad>}
 */
API.Client.TeamSquadApi.prototype.v2TeamsIdSquadPatch = function(squadMembers, id, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v2/teams/{id}/squad'
      .replace('{' + 'id' + '}', String(id));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'squadMembers' is set
  if (!squadMembers) {
    throw new Error('Missing required parameter squadMembers when calling v2TeamsIdSquadPatch');
  }
  // verify required parameter 'id' is set
  if (!id) {
    throw new Error('Missing required parameter id when calling v2TeamsIdSquadPatch');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'PATCH',
    url: path,
    json: true,
    data: squadMembers,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
