/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface V2LineupInput {
    "status"?: V2LineupInput.StatusEnum;
    "homeTeam"?: models.V2LineupTeamInput;
    "awayTeam"?: models.V2LineupTeamInput;
}

export namespace V2LineupInput {
    export enum StatusEnum {
        CONFIRMED = <any> 'CONFIRMED',
        UNCONFIRMED = <any> 'UNCONFIRMED'
    }
}
