/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.AssetsApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * API for accessing various kinds of football data, updated in real time.
 * Version: 0.0.1
 * Generated by: io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
 */
goog.provide('API.Client.AssetsApi');

goog.require('API.Client.v2_Asset');
goog.require('API.Client.v2_AssetInput');

/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.AssetsApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('AssetsApiBasePath') ?
                   /** @type {!string} */ ($injector.get('AssetsApiBasePath')) :
                   'https://false';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('AssetsApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('AssetsApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.AssetsApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * 
 * Bulk delete assets
 * @param {!Array<!API.Client.v2_AssetInput>=} opt_assets Array of assets
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.AssetsApi.prototype.v2AssetsDelete = function(opt_assets, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v2/assets';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'DELETE',
    url: path,
    json: true,
    data: opt_assets,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Bulk Upsert assets
 * @param {!Array<!API.Client.v2_AssetInput>=} opt_assets Array of assets
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.v2_Asset>}
 */
API.Client.AssetsApi.prototype.v2AssetsPost = function(opt_assets, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/v2/assets';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'POST',
    url: path,
    json: true,
    data: opt_assets,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
