/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { autoinject } from 'aurelia-framework';
import { HttpClient } from 'aurelia-http-client';
import { Api } from './Api';
import { AuthStorage } from './AuthStorage';
import {
  V2Lineup,
  Lineup,
  V2LineupInput,
} from './models';

/**
 * lineupsGet - parameters interface
 */
export interface ILineupsGetParams {
  acceptLanguage?: string;
  lastUpdate?: Date;
}

/**
 * v2MatchesIdLineupsGet - parameters interface
 */
export interface IV2MatchesIdLineupsGetParams {
  id: string;
  languageCode?: string;
}

/**
 * v2MatchesIdLineupsPut - parameters interface
 */
export interface IV2MatchesIdLineupsPutParams {
  lineup: V2LineupInput;
  id: string;
}

/**
 * LineupsApi - API class
 */
@autoinject()
export class LineupsApi extends Api {

  /**
   * Creates a new LineupsApi class.
   *
   * @param httpClient The Aurelia HTTP client to be injected.
   * @param authStorage A storage for authentication data.
   */
  constructor(httpClient: HttpClient, authStorage: AuthStorage) {
    super(httpClient, authStorage);
  }

  /**
   * Get lineup information. Includes players, formation and coach
   * @param params.acceptLanguage List of acceptable human languages for response. https://en.wikipedia.org/wiki/Content_negotiation
   * @param params.lastUpdate Filter lineups which have updates only after the specified time
   */
  async lineupsGet(params: ILineupsGetParams): Promise<Array<Lineup>> {
    // Verify required parameters are set

    // Create URL to call
    const url = `${this.basePath}/lineups`;

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'last_update': params['lastUpdate'],
      })
      .withHeader('Accept-Language', params['acceptLanguage'])
      // Authentication 'basicAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Get lineups by match id
   * @param params.id Unique identifier of the resource.
   * @param params.languageCode Returns translated response based on the language code
   */
  async v2MatchesIdLineupsGet(params: IV2MatchesIdLineupsGetParams): Promise<V2Lineup> {
    // Verify required parameters are set
    this.ensureParamIsSet('v2MatchesIdLineupsGet', params, 'id');

    // Create URL to call
    const url = `${this.basePath}/v2/matches/{id}/lineups`
      .replace(`{${'id'}}`, encodeURIComponent(`${params['id']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asGet()
      // Set query parameters
      .withParams({ 
        'language_code': params['languageCode'],
      })

      // Authentication 'basicAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

  /**
   * Update Lineup information
   * @param params.lineup Lineup information to save in persistance
   * @param params.id Unique identifier of the resource.
   */
  async v2MatchesIdLineupsPut(params: IV2MatchesIdLineupsPutParams): Promise<V2Lineup> {
    // Verify required parameters are set
    this.ensureParamIsSet('v2MatchesIdLineupsPut', params, 'lineup');
    this.ensureParamIsSet('v2MatchesIdLineupsPut', params, 'id');

    // Create URL to call
    const url = `${this.basePath}/v2/matches/{id}/lineups`
      .replace(`{${'id'}}`, encodeURIComponent(`${params['id']}`));

    const response = await this.httpClient.createRequest(url)
      // Set HTTP method
      .asPut()
      // Encode body parameter
      .withHeader('content-type', 'application/json')
      .withContent(JSON.stringify(params['lineup'] || {}))

      // Authentication 'basicAuth' required
      // Send the request
      .send();

    if (response.statusCode < 200 || response.statusCode >= 300) {
      throw new Error(response.content);
    }

    // Extract the content
    return response.content;
  }

}

