/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlayerStatsExtendedAllOf {
    /**
    * Goals conceded (Goalkeeper)
    */
    'conceded'?: number;
    /**
    * Games started as a substitute
    */
    'substitute'?: number;
    /**
    * Games without allowing a goal (Goalkeeper)
    */
    'cleansheets'?: number;
    /**
    * Games where the player has come on
    */
    'substituteIn'?: number;
    /**
    * Games where the player has come off
    */
    'substituteOut'?: number;
    /**
    * Minutes played after coming on as a substitute
    */
    'minutesSubstitute'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conceded",
            "baseName": "conceded",
            "type": "number",
            "format": ""
        },
        {
            "name": "substitute",
            "baseName": "substitute",
            "type": "number",
            "format": ""
        },
        {
            "name": "cleansheets",
            "baseName": "cleansheets",
            "type": "number",
            "format": ""
        },
        {
            "name": "substituteIn",
            "baseName": "substitute_in",
            "type": "number",
            "format": ""
        },
        {
            "name": "substituteOut",
            "baseName": "substitute_out",
            "type": "number",
            "format": ""
        },
        {
            "name": "minutesSubstitute",
            "baseName": "minutes_substitute",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerStatsExtendedAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

