/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V2LeagueEntryInput {
    'rank'?: number;
    'teamId'?: string;
    'played'?: number;
    'wins'?: number;
    'draws'?: number;
    'losses'?: number;
    'points'?: number;
    'goalsFor'?: number;
    'goalsAgainst'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rank",
            "baseName": "rank",
            "type": "number",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "played",
            "baseName": "played",
            "type": "number",
            "format": ""
        },
        {
            "name": "wins",
            "baseName": "wins",
            "type": "number",
            "format": ""
        },
        {
            "name": "draws",
            "baseName": "draws",
            "type": "number",
            "format": ""
        },
        {
            "name": "losses",
            "baseName": "losses",
            "type": "number",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "goalsFor",
            "baseName": "goals_for",
            "type": "number",
            "format": ""
        },
        {
            "name": "goalsAgainst",
            "baseName": "goals_against",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2LeagueEntryInput.attributeTypeMap;
    }

    public constructor() {
    }
}

