/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2Player } from './V2Player';
import { HttpFile } from '../http/http';

export class V2SquadPlayer {
    'player': V2Player;
    'status': V2SquadPlayerStatusEnum;
    'contractType'?: V2SquadPlayerContractTypeEnum;
    'startDate'?: string;
    'endDate'?: string;
    'shirtNumber'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "player",
            "baseName": "player",
            "type": "V2Player",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "V2SquadPlayerStatusEnum",
            "format": ""
        },
        {
            "name": "contractType",
            "baseName": "contract_type",
            "type": "V2SquadPlayerContractTypeEnum",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "shirtNumber",
            "baseName": "shirt_number",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2SquadPlayer.attributeTypeMap;
    }

    public constructor() {
    }
}


export type V2SquadPlayerStatusEnum = "ACTIVE" | "INACTIVE" ;
export type V2SquadPlayerContractTypeEnum = "PERMANENT" | "LOAN" | "UNKNOWN" ;

