/**
 * Football API
 * API for accessing various kinds of football data, updated in real time.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2TeamColorsColorsInner } from './V2TeamColorsColorsInner';
import { HttpFile } from '../http/http';

export class V2TeamColors {
    'entityType': string;
    'entityId': string;
    'colors': Array<V2TeamColorsColorsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityId",
            "baseName": "entity_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "colors",
            "baseName": "colors",
            "type": "Array<V2TeamColorsColorsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2TeamColors.attributeTypeMap;
    }

    public constructor() {
    }
}

